import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import TodoItem from "@/components/Todo/TodoItem";
import TodoList from "@/components/Todo/TodoList";
import styles from "./index.module.scss"
import {TodoItemModel} from "@/models/TodoItem";
import {useEffect, useRef, useState} from "react";

const inter = Inter({subsets: ['latin']})

// export async function getServerSideProps(context) {
//     const todoList = await getTodoList();
//     return {
//         props: {todoList}, // will be passed to the page component as props
//     }
// }

export default function Home(props: { todoList: TodoItemModel[] }) {
    const [todoList, setTodoList] = useState<TodoItemModel[]>([]);
    useEffect(() => {
        (async () => {
            const todoList = await getTodoList();
            setTodoList(todoList);
            console.log(todoList);
        })();
    }, []);
    return (
        <>
            <Head>
                <title>TodoApp</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <TodoList todoList={todoList} setTodoList={setTodoList}/>

            </main>
        </>
    )
}

const getTodoList = async (): Promise<TodoItemModel[]> => {
    try {
        const response = await fetch("http://127.0.0.1:8000/api/items");
        if (response.ok) {
            return await response.json();
        }
    }
    catch (e) {
        console.log(e);
    }

    return [];
}
